### ISSUE TITLE
Tbh I am not sure that I understand the description of this mod. 

### ISSUE THREAD

**Issue by KosmosisDire** [WondaMegapon/ArtifactOfWayfaring#1]
Can't you already play through all the stages in a loop by just switching the teleporter at the end of Sky Meadow? I am sure I am just misunderstanding, but a little more detail would be nice, at least in the readme. (Also maybe add the readme to GitHub as well) (sorry for the non-issue issue haha)

**Comment by WondaMegapon** [comment]
Wonderful question! I've been having difficulties finding a way to succinctly describe the mod. 😅

Essentially, the mod alters it so every available stage is played per loop. Both Titanic Plains and Distant Roost occur back-to-back. Sundered Grove, Abyssal Depths, and Rallypoint Delta are played before you even reach Sky Meadows. You have to get through all ten naturally-occurring stages in the game before you loop again.

If you have any suggestions for brief descriptions, please pass 'em by. It'd help tons.

**Comment by KosmosisDire** [comment]
How about:
Adds an artifact that makes all 10 stage variants appear in a loop, allowing the player to visit every stage before returning to the first.

**Comment by WondaMegapon** [comment]
Wonderful! I think I really vibe with that description. I'll quickly see if I can replace that.
